### ISSUE TITLE
Support for LLVM 3.5

### ISSUE THREAD

**Issue by davorb** [sellout/CL-LLVM#15]
Hey,

In case anyone needs help compiling this for LLVM 3.5, you will have to remove the line

`((:linker-private-weak-auto "LLVMLinkerPrivateWeakDefAutoLinkage"))`

from `grovel.lisp`. After you've done that, it works just fine (at least on OS X with SBCL).

**Comment by Rudolph-Miller** [comment]
It's fixed with https://github.com/sellout/CL-LLVM/pull/16

**Comment by sellout** [comment]
Thanks, @Rudolph-Miller!

**Comment by Rudolph-Miller** [comment]
My pleasure! :smile:
